name: ML Training Pipeline

on:
  push:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r mlops-learning/requirements.txt

      - name: Run ML training
        run: python mlops-learning/train.py